# This is free software, lisence use MIT.

name: OpenWrt-configer

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-23.05
  CONFIG_FILE: .config

jobs:
  config_openwrt:
  
