name: Test

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: openwrt-23.05

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Get version of openwrt
      run: |
        version=$(echo $REPO_BRANCH | sed "s/openwrt-//g")
        echo $version