name: Configer Test

on:
  workflow_dispatch:
    inputs:
      ENABLE_SSH:
        description: '开启SSH连接'
        required: true
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Save Config File
      run: |
        mkdir $GITHUB_REPOSITORY/config
        echo "test config file" > $GITHUB_REPOSITORY/config/test.config
