name: OpenWrt Configer

on:
  workflow_dispatch:
    inputs:
      ENABLE_SSH:
        description: '开启SSH连接'
        required: false
        default: true
        type: boolean

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        
        - name: SSH connection to Actions
          uses: valeriangalliat/action-sshd-cloudflared@v2
          timeout-minutes: 360
          continue-on-error: true